### ISSUE TITLE
Decompression of EDN files?

### ISSUE THREAD

**Issue by miccTronic** [felinis/RoomEditImproved#1]
Hi felnis, I like you work on the Room Editor for Project Eden very much. I am trying myself to visualize some of the environments from the game. However, it seems that my game files don't correspond to the format you are using. In fact, the EDN files always start with "COMP", probably indicating that they are compressed. Is the project based on a different version of the game? Or am I just missing a way to decompress the levels? In any case, help is greatly appreciated! :-)

Here's an example of the first level.

![Screenshot 2024-04-04 104032](https://github.com/felinis/RoomEditImproved/assets/104464771/86f13972-974a-40e5-893d-97039f89ee93)

Best, mic

**Comment by felinis** [comment]
Hi miccTronic,

I appreciate your interest in my project. You are correct, the files that come with the game are compressed by default, more specifically using some sort of LZ compression with a 1024 byte table. I haven't yet figured out what the name of the algorithm was.

A while ago I wrote a decompression tool that I successfully used on all the level files, you can download it [here](https://drive.google.com/file/d/1NFwHWFY2AP5hLkuTMopjcxrZwouTUzJg/view?usp=drivesdk). Once you decompress the levels (just drag&drop an EDN file onto edndec), they are able to be loaded inside Room Editor and even the game itself! I think I lost the source code to it, but it shouldn't be very difficult to rewrite it.

Best regards,
Alan

**Comment by felinis** [comment]
By the way, I should also update the code in this repo since it is outdated and does not reflect the actual state of the program. I will do as soon as possible.

**Comment by miccTronic** [comment]
Hi Alan, thanks a lot for the quick reply and for sharing the tool, that's amazing! I'm not very familiar with compression so probably wouldn't have come up with that otherwise.
Of course if you have time, any update to the project will also be interesting for me to look at. Likewise, if I discover something new about the files, I'll let you know. :-)

**Comment by felinis** [comment]
Great, very appreciated! Contributions are welcome. :)
I updated the repo with the latest code.

**Comment by felinis** [comment]
For the sake of completeness, the source code for the decompression utility can be found [here](https://github.com/hogsy/formats/tree/main/templates/core/edn_decompression).
